name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Assignment1-HadiCynthia
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 18

      - name: Install packages
        run: npm ci
        working-directory: ./wordle-web

      - name: Build App
        run: npm run generate
        working-directory: ./wordle-web

      - name: Vitest
        run: npm run test
        working-directory: ./wordle-web  

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_TREE_002DF5010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/website/.output/public' # App source code path
          output_location: '' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

